name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - "main"

env:
  AZURE_LOCATION: westeurope

permissions:
  id-token: write

jobs:
  build:
    name: Provision Azure Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login with service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Generate deployment name
        id: random
        run: echo "::set-output name=value::`openssl rand -hex 2`"

      - name: Apply bicep template
        uses: azure/cli@v1
        with:
          inlineScript: az deployment sub create --name gh-${{ steps.random.outputs.value }} --location ${{ env.AZURE_LOCATION}} --template-file main.bicep --parameters main.parameters.json